name: Triage & route issues

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: read

jobs:
  route:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'team:DocsEng' ||
      github.event.label.name == 'team:Obs' ||
      github.event.label.name == 'team:Platform' ||
      github.event.label.name == 'team:Projects' ||
      github.event.label.name == 'team:Search' ||
      github.event.label.name == 'team:Security'
    env:
      PROJECT_ID_MAP: |
        {
          "team:DocsEng":   "1625",
          "team:Obs":       "649",
          "team:Platform":  "1232",
          "team:Projects":  "1415",
          "team:Search":    "726",
          "team:Security":  "1034"
        }
    steps:
      - name: Remove needs-team label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: needs-team

      - name: Add issue to the right project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/orgs/elastic/projects/${{ fromJson(env.PROJECT_ID_MAP)[github.event.label.name] }}
          github-token: ${{ secrets.ADD_TO_BOARD_TOKEN }}
          labeled: ${{ github.event.label.name }}
          label-operator: OR
